"""hdf5 generation output: layout, manifest fields and reader round trips, from the streamed build."""

from __future__ import annotations

import json
from pathlib import Path

import h5py
import numpy as np
import pytest
from numpy.typing import NDArray

from neuralls.composition.generation.dataset_builder import build_dataset
from neuralls.domain.generation.specs import DatasetSpec, MixtureSpec, SourceSpec
from neuralls.platform.config.dataset_entries import entry_from_path
from neuralls.platform.storage.dataset_readers import resolve_dataset_artifacts
from neuralls.platform.storage.manifest_io import load_dataset_manifest
from neuralls.platform.storage.training_artifacts import Hdf5ArraySource, load_training_arrays

_SAMPLE_COUNT = 5
_DATASET_FILE = "dataset.h5"


@pytest.fixture
def two_by_two() -> NDArray[np.float64]:
    """2x2 SPD matrix, written to disk as the generation source."""
    return np.array([[3.0, 1.0], [1.0, 7.0]], dtype=np.float64)


@pytest.fixture
def matrix_file(tmp_path: Path, two_by_two: NDArray[np.float64]) -> Path:
    path = tmp_path / "matrix.npy"
    np.save(path, two_by_two)
    return path


@pytest.fixture
def streamed_hdf5_dir(tmp_path: Path, matrix_file: Path) -> Path:
    """A hdf5 dataset generated by the streamed writer, with _SAMPLE_COUNT rows."""
    dataset_dir = tmp_path / "dataset"
    build_dataset(
        SourceSpec(matrix_path=str(matrix_file)),
        DatasetSpec(
            mixture=MixtureSpec(counts={"gaussian_forward": _SAMPLE_COUNT}, seed=0, shuffle=False),
            normalize="none",
        ),
        str(dataset_dir),
        dataset_format="hdf5",
    )
    return dataset_dir


def test_streamed_build_creates_single_h5_file(streamed_hdf5_dir: Path) -> None:
    assert (streamed_hdf5_dir / _DATASET_FILE).is_file()


def test_streamed_build_h5_contains_expected_datasets(streamed_hdf5_dir: Path) -> None:
    with h5py.File(str(streamed_hdf5_dir / _DATASET_FILE), "r") as f:
        assert "matrix" in f
        assert "rhs" in f
        assert "solutions" in f


def test_streamed_manifest_schema_and_format(streamed_hdf5_dir: Path) -> None:
    """manifest.json has the dataset schema and every artifact format set to 'hdf5'."""
    manifest = load_dataset_manifest(streamed_hdf5_dir)
    assert str(manifest["schema"]).startswith("neuralls.dataset")
    assert manifest["matrix"]["format"] == "hdf5"
    assert manifest["rhs"]["format"] == "hdf5"
    assert manifest["solutions"]["format"] == "hdf5"


def test_streamed_manifest_artifact_paths_and_keys(streamed_hdf5_dir: Path) -> None:
    """Manifest stores path='dataset.h5' and key='<dataset>' as separate fields."""
    manifest = load_dataset_manifest(streamed_hdf5_dir)
    assert manifest["matrix"]["path"] == _DATASET_FILE
    assert manifest["matrix"]["key"] == "matrix"
    assert manifest["rhs"]["path"] == _DATASET_FILE
    assert manifest["rhs"]["key"] == "rhs"
    assert manifest["solutions"]["path"] == _DATASET_FILE
    assert manifest["solutions"]["key"] == "solutions"


def test_streamed_roundtrip_shapes_and_each_row_solves(
    streamed_hdf5_dir: Path, two_by_two: NDArray[np.float64]
) -> None:
    """Reader round trip: sample count matches the plan and every stored row solves the stored matrix."""
    arrays = load_training_arrays(streamed_hdf5_dir)
    assert isinstance(arrays.rhs_source, Hdf5ArraySource)
    assert arrays.rhs_source.key == "rhs"
    assert arrays.sample_count == _SAMPLE_COUNT

    with h5py.File(str(streamed_hdf5_dir / _DATASET_FILE), "r") as f:
        rhs = np.asarray(f["rhs"])
        solutions = np.asarray(f["solutions"])
    np.testing.assert_allclose(arrays.rhs_source.load_sample(0), rhs[0])
    np.testing.assert_allclose(solutions @ two_by_two.T, rhs, atol=1e-8)


def test_resolve_artifacts_exposes_hdf5_keys(streamed_hdf5_dir: Path) -> None:
    """resolve_dataset_artifacts() exposes the key field from the manifest artifact."""
    artifacts = resolve_dataset_artifacts(streamed_hdf5_dir)
    assert artifacts.rhs.key == "rhs"
    assert artifacts.solutions.key == "solutions"
    assert artifacts.matrix.key == "matrix"
    assert artifacts.rhs.path == streamed_hdf5_dir / _DATASET_FILE


def test_entry_from_path_returns_hdf5_entry(tmp_path: Path) -> None:
    """entry_from_path returns Hdf5Entry for .h5 suffix with correct key."""
    from dlkit.infrastructure.config.data_entries import Hdf5Entry

    path = tmp_path / _DATASET_FILE
    path.touch()  # Hdf5Entry validates existence
    entry = entry_from_path(path, name="x", model_input=True, role="feature", key="rhs")

    assert isinstance(entry, Hdf5Entry)
    assert entry.key == "rhs"
    assert entry.path == path


def test_streamed_parameter_arrays_are_stored_under_indexed_keys(
    tmp_path: Path, matrix_file: Path
) -> None:
    """Parameter streams are stored in dataset.h5 under 'parameters_<i>' and listed in the manifest."""
    params = np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=np.float64)
    params_file = tmp_path / "params.npy"
    np.save(params_file, params)
    dataset_dir = tmp_path / "dataset"

    build_dataset(
        SourceSpec(matrix_path=str(matrix_file), parameters_paths=(str(params_file),)),
        DatasetSpec(
            mixture=MixtureSpec(counts={"gaussian_forward": 3}, seed=0, shuffle=False),
            normalize="none",
        ),
        str(dataset_dir),
        dataset_format="hdf5",
    )

    manifest = json.loads((dataset_dir / "manifest.json").read_text(encoding="utf-8"))
    param_entries = manifest["params"]
    assert len(param_entries) == 1
    assert param_entries[0]["path"] == _DATASET_FILE
    assert param_entries[0]["key"] == "parameters_0"
    assert param_entries[0]["format"] == "hdf5"

    with h5py.File(str(dataset_dir / _DATASET_FILE), "r") as f:
        assert f["parameters_0"].shape[0] == 3
