"""Full per-case pipeline: sequence the generate, train, and compare stages."""

from __future__ import annotations

from pathlib import Path

from neuralls.application.models import AssignmentResult
from neuralls.composition.assignments.assembler import load_validated_case_config
from neuralls.composition.assignments.comparison_batch import run_comparison_batch
from neuralls.composition.assignments.training_batch import run_assignment_sweep
from neuralls.composition.comparison.models import ComparisonOutcome, ComparisonParams
from neuralls.composition.generation.multi_generation import generate_batch
from neuralls.platform.config.settings import NeurallsSettings, require_settings


def run_case_pipeline(
    case_config_path: Path,
    settings: NeurallsSettings | None = None,
    *,
    force_generate: bool = False,
    force_train: bool = False,
    force_compare: bool = False,
    force_expand: bool = False,
) -> tuple[list[AssignmentResult], list[ComparisonOutcome]]:
    """Run the full pipeline for one case config: generate, train, then compare.

    Sequences the exact same three stage functions `neuralls generate`/`train`/
    `compare` call directly — `generate_batch()`, `run_assignment_sweep()`, and
    `run_comparison_batch()` — adding no stage logic of its own. Each stage
    keeps its own independent reuse check, so a dataset regenerated by stage 1
    automatically cascades into retraining (stage 2, via its dataset-hash
    reuse check) and recomparing (stage 3, via its checkpoint-dependency reuse
    check) exactly the affected assignments/comparisons, without invoking
    three separate commands by hand. Training and comparisons are each
    skipped entirely when the case config declares none — a case config may
    legitimately declare only `[[comparisons]]` with preconditioners inline
    in `comparison_defaults` (e.g. POD-2G weighting variants that need the
    matrix at fit time, which a checkpoint-backed `fit` job can't provide).

    Args:
        case_config_path: Path to a case config defining datasets, assignments,
            and (optionally) comparisons.
        settings: Optional pre-loaded runtime settings.
        force_generate: Regenerate every dataset even if a matching one exists.
        force_train: Retrain every assignment even if a completed run exists.
        force_compare: Rerun every comparison even if a matching one exists.
        force_expand: Recreate sweep-generated dataset configs even if present.

    Returns:
        Tuple of (assignment results, comparison outcomes). Each list is
        empty when the case config declares no `[[assignments]]` /
        `[[comparisons]]` respectively.
    """
    settings = require_settings(settings, case_config_path=case_config_path)
    cfg, config_dir = load_validated_case_config(
        case_config_path, settings, force_expand=force_expand
    )

    generate_batch(cfg, config_dir, settings, force=force_generate)

    assignment_results: list[AssignmentResult] = []
    if cfg.assignments:
        sweep_result = run_assignment_sweep(
            case_config_path,
            settings=settings,
            force=force_train,
        )
        assignment_results = sweep_result.results

    if not cfg.comparisons:
        return assignment_results, []

    comparison_outcomes = run_comparison_batch(
        case_config_path,
        ComparisonParams(force=force_compare),
        settings=settings,
    )
    return assignment_results, comparison_outcomes
