[run]
type = "fit"
seed = 42
precision = "64"
data = "../../profiles/data/array-default.toml"

[model]
name = "PODCoarseningFittable"
module_path = "neuralls.composition.preconditioners.pod_fittable"
rank = 300
